In [4]:
import numpy as np
from stateFactory import generate_valid_state

In [9]:
s = generate_valid_state()
print(s.board)

[[1 4 0 2 5 8 3 0 9]
 [2 5 8 3 6 9 4 7 1]
 [3 0 9 4 7 1 0 8 2]
 [4 7 1 5 0 2 6 9 3]
 [5 8 2 6 9 3 7 1 4]
 [6 9 3 7 1 0 8 2 5]
 [7 1 4 8 2 5 9 3 6]
 [0 2 5 9 3 6 1 4 7]
 [9 3 0 1 4 7 2 5 8]]


In [24]:
def one_hot_encode(state: np.ndarray) -> np.ndarray:
    return (np.arange(state.max()) == state[...,None]-1).astype(int)

In [25]:
one_hot_encode(s.board)

array([[[1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1]],

       [[0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0